### ISSUE TITLE
Operator precedence issue

### ISSUE THREAD

**Issue by jed** [cloudfour/elastic-textarea#5]
[This line](https://github.com/cloudfour/elastic-textarea/blob/c9c5af51a911aa6aa3a819246311ed10d18d2dc2/index.js#L20):
```js
if (!target instanceof HTMLTextAreaElement) return;
```
parses as this:
```js
if ((!target) instanceof HTMLTextAreaElement) return;
```
but you probably intended this:
```js
if (!(target instanceof HTMLTextAreaElement)) return;
```

**Comment by Paul-Hebert** [comment]
Thanks @jed, great catch! I'll be releasing a fix for this a little later today
